// <auto-generated />
using System;
using EventBookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventBookingAPI.Migrations
{
    [DbContext(typeof(EventBookingContext))]
    [Migration("20260415125806_AddAuthInfo")]
    partial class AddAuthInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EventBookingAPI.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("booking_time");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("EventBookingAPI.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tag");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Capacity = 50,
                            Description = "Join the world's most innovative minds for three days of immersive exploration into the future of technology.",
                            EventDate = new DateTime(2024, 10, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCvGkENIWPDy4TRzlnkgM424Lvmip--1JIIakXEublw3QtgVZUO7-hliKlQ87ZIx_d54BUEua_2fMBOxgNgXaxse14e399RKb1Xc8WdTeqhThGrrBcKAOoJExFcv6Xdvaipp8AmK4U0eNV_oW1KdAZOgxykr7MykTRDeMnu7DxTFcwY56uGRMV3VAM4jMgPsMWYDizjakJYXmNMpLLrpVPwG_gDwePv5rC90ATocgvISE_RLSeaVoolVGSGCeb5z0J2n-i7PUjx7Kg",
                            Location = "Monaco Yacht Club",
                            Price = 2400m,
                            Tag = "Urgent",
                            Title = "The Celestial Soirée"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Capacity = 100,
                            Description = "Immersive exploration into the future of technology and quantum computing breakthroughs.",
                            EventDate = new DateTime(2024, 11, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBmbRv6GuTGGjKh3p0AhtTfYWSftNgc-Gc-Tu_RhFdpSsacx-SiFWpacdeU_XNkItBROVt-maUEbGwxJpe4-nDMFD_gs8zY6_ycn81qV6oNELMaTxnfSLt7xQ2tbcbLD2WvFdKDu5Ryn1hV-cmWwyl_doWoH_-9QBnybx8B1BXuL20WAzFmevr4zfZLktOjW6xylKHpdeyJeYr6YPzlSlvB5tUXZuO0povkrONtGtmhlwfRWtl8lhf2DqnT2avC4NUBvL4VzzdAhUI",
                            Location = "The Ritz-Carlton, Tokyo",
                            Price = 850m,
                            Tag = "Summit",
                            Title = "Quantum Nexus 2024"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Capacity = 200,
                            Description = "Exclusive art exhibition showcasing minimalist contemporary sculptures on pedestals.",
                            EventDate = new DateTime(2024, 12, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCSEcqyhxN2gOg-s3dPxgVYxSAJEGGvKoES2x_SBdH0cltn8Si5oRN9Y3x3lmhR7qMoVKdHYdnIKsvRLxnZz3mQyuWQHUQp3Yi9zst6J09mMAzuuMyQ6UIULg3tSUo9ntOpmuONYzs2XYrrMO-v0e6hjZHLjtVzrGkY_crfYof1Eke6wn2DYGa5uKnW91Hiq0VZDDvXXNTMgnr978T4Vc8rD4FfYi_186ae-00gvAYVSfusySKDKxtlzBY5o4j2gtFzHd2OHnb4AsA",
                            Location = "Gagosian Gallery, NYC",
                            Price = 120m,
                            Tag = "Exhibition",
                            Title = "Visions of the Void"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Capacity = 30,
                            Description = "Sunset over rolling vineyard hills with rows of grapevines and a rustic stone villa.",
                            EventDate = new DateTime(2024, 10, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBNdZY1P57wf2iuWDV9TGD9Kkat74q3_IEvyN8mTi4CoGj7jZkPsADtB7I_NiTW3EQBcqBnh49M0ZVR_qs0f3qu8KgbjKmfIS97l6iXZBBqNXGjJfejQU5UQ0x4CxXf7GQtkytQoVIqRpHuc_HHxG5uPaBtEXsC85TAxHn_BPMghMFjOWlDy2ToAelyy7oI3MbKM7XYbBgGJ2rKbLUSkbWiOi1KD74xaSkDy_BUT8mq2IhcoBvB-0CYhU3sp8-9w7KQmv6JGG9qlUw",
                            Location = "Castello di Ama, Tuscany",
                            Price = 3750m,
                            Tag = "Exclusive Retreat",
                            Title = "Tuscan Harvest Weekend"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Capacity = 80,
                            Description = "Intimate jazz club setting with warm lighting, a grand piano, and soft silhouettes of performers.",
                            EventDate = new DateTime(2024, 11, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCnrtxndFw8m4ZqjOg1oEYrh1mYCDguAqGXm-e-_obeTiZFMFvknBNDIhNei5HahyGchwH-H9nznKslm_ibWChi0we8ZnffbW3yw1II5MzcTpSaR1BcDauD0N9TciipyoTz_ljeMeRLG8pCEh1BcGZ271BvnYPhkd6UdCfU4VPOOu0Ptvf3Aw5PQ9NdA6eR0d1LQtuaHRPzAgP2f1CahHeGwDXb9qC7RQ9isitKnRn80FB7WQYKq4od5jLnWTh86qLDW-Rrw1mhrqc",
                            Location = "Saint-Germain-des-Prés, Paris",
                            Price = 185m,
                            Tag = "Live Performance",
                            Title = "Blue Note Sessions"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Capacity = 500,
                            Description = "Focuses on how integrated systems create seamless experiences for end-users across global infrastructures.",
                            EventDate = new DateTime(2024, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDRveXypyiMbHbaEnHAvtn41EcT6GJ68rsRClmQQkRIf8LzI7iHTzzXX67vwvnyWBviNfeY9i5TwEPp90IYmYW_Q2L5x-bGuA-6BomqjqLwul-rTXx-kSLa0rzhVElr0U-p3hZWc1N-ZZFagXsUTk_oVvSEf_aOXtzEELoKH84at80F4_ATvi923bS_E4CevM6DoicY_ZJx2tVYgi8HGGIzZ7fQ0MJ88okUivjrjJ1lSrqNQaHUIHuMb9dc79NtqFKcKegR4AyEfDQ",
                            Location = "Grand Marina Pavilion, SF",
                            Price = 850m,
                            Tag = "Technology",
                            Title = "Global Tech Summit 2024"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Capacity = 1000,
                            Description = "A grand architectural view of a modern symphony hall with warm wooden panels.",
                            EventDate = new DateTime(2024, 10, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDuq4takxdmRKsf5Jqu87OMUCSeb4zHMBgS5WReSut7Fqbt3jZmpZPtUl9TTIXEeLXpbT-Xfmt9Lc57trLeOcGyR-Zx2LCeXjB8HOImcWz61njFh1_8wlvx_eZDyrX9mRRDub8URlyXnyTN4ARsn7INFmfmfKvNpewN1QQqkL6KEbMnibkfF-QbfAEOQpFhVw8Q-9dWclb6WKvnr1Rlfn_LbH_8PcjSjL8xRThNknrpJZvjwOMuSTss79qqG95Ir4CdqIabsR5SWPo",
                            Location = "The Glass Pavilion, London",
                            Price = 120m,
                            Tag = "Gala",
                            Title = "Annual Symphony Gala"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Capacity = 150,
                            Description = "Transforming supply chain ecosystems using bleeding edge automated sorting and AI-driven node logistics.",
                            EventDate = new DateTime(2024, 12, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1579621970588-a35d0e7ab9b6?auto=format&fit=crop&q=80",
                            Location = "Messe Frankfurt",
                            Price = 350m,
                            Tag = "Seminar",
                            Title = "Future of Logistics Seminar"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Capacity = 20,
                            Description = "A 10-course experiential dining pop-up exploring the nexus of gastronomy and molecular science.",
                            EventDate = new DateTime(2024, 11, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80",
                            Location = "Noma Test Kitchen, CPH",
                            Price = 1450m,
                            Tag = "Pop-Up",
                            Title = "Culinary Avant-Garde"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Capacity = 40,
                            Description = "Intimate weekend retreat focusing on narrative design, rapid prototyping, and self-publishing pipelines.",
                            EventDate = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80",
                            Location = "Lake Tahoe Cabin Resort",
                            Price = 450m,
                            Tag = "Retreat",
                            Title = "Indie Game Developers Retreat"
                        });
                });

            modelBuilder.Entity("EventBookingAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("EventBookingAPI.Models.Booking", b =>
                {
                    b.HasOne("EventBookingAPI.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingAPI.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventBookingAPI.Models.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventBookingAPI.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
